### ISSUE TITLE
Check if service already running

### ISSUE THREAD

**Issue by born-slippy** [CERIT-SC/puppet-open_vm_tools#1]
Would it be possible to get this module to check if the service is already installed and running instead of always trying to start the service?  Get this error after open-vm-tools was installed and started (Ubuntu 14.04.1):

Error: Could not start Service[open-vm-tools]: Execution of '/etc/init.d/open-vm-tools start' returned 1: \* Starting open-vm daemon vmtoolsd
Wrapped exception:
Execution of '/etc/init.d/open-vm-tools start' returned 1: \* Starting open-vm daemon vmtoolsd
Error: /Stage[main]/Open_vm_tools::Service/Service[open-vm-tools]/ensure: change from stopped to running failed: Could not start Service[open-vm-tools]: Execution of '/etc/init.d/open-vm-tools start' returned 1: \* Starting open-vm daemon vmtoolsd
Notice: /Stage[main]/Open_vm_tools/Anchor[open_vm_tools::end]: Dependency Service[open-vm-tools] has failures: true
Warning: /Stage[main]/Open_vm_tools/Anchor[open_vm_tools::end]: Skipping because of failed dependencies

**Comment by vholer** [comment]
I have fixed service checks on Debian/Ubuntu. New module ver. 0.9.3 has been released on Puppet Forge. Thank you for your report, please reopen in case you think the problem persists.
